-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-11-02 20:02:49 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE tbl_alumnos (
    codigo_alumno NUMBER NOT NULL,
    promedio      NUMBER,
    cuenta        NUMBER,
    color_de_ojos VARCHAR2(100)
);

ALTER TABLE tbl_alumnos ADD CONSTRAINT tbl_alumnos_pk PRIMARY KEY ( codigo_alumno );

CREATE TABLE tbl_alumnos_x_carreras (
    codigo_alumno             NUMBER NOT NULL,
    codigo_carrera            NUMBER NOT NULL,
    promedio                  NUMBER,
    fecha_ingreso             DATE,
    cantidad_clases_aprobadas NUMBER
);

ALTER TABLE tbl_alumnos_x_carreras ADD CONSTRAINT tbl_alumnos_x_carreras_pk PRIMARY KEY ( codigo_alumno,
                                                                                          codigo_carrera );

CREATE TABLE tbl_asignaturas (
    codigo_asignatura NUMBER NOT NULL,
    codigo_carrera    NUMBER NOT NULL,
    nombre            VARCHAR2(200),
    uv                NUMBER
);

COMMENT ON COLUMN tbl_asignaturas.codigo_carrera IS
    'ESTE CODIGO DE CARRERA ES LA CARRERA DUEÑNA DE LA CLASE';

ALTER TABLE tbl_asignaturas ADD CONSTRAINT tbl_asignaturas_pk PRIMARY KEY ( codigo_asignatura );

CREATE TABLE tbl_carreras (
    codigo_carrera     NUMBER NOT NULL,
    nombre_carrera     VARCHAR2(100),
    cantidad_clases    NUMBER,
    codigo_jefe        NUMBER NOT NULL,
    codigo_coordinador NUMBER NOT NULL
);

ALTER TABLE tbl_carreras ADD CONSTRAINT tbl_carreras_pk PRIMARY KEY ( codigo_carrera );

CREATE TABLE tbl_categorias_maestros (
    codigo_categoria NUMBER NOT NULL,
    nombre_categoria VARCHAR2(200)
);

ALTER TABLE tbl_categorias_maestros ADD CONSTRAINT tbl_categorias_maestros_pk PRIMARY KEY ( codigo_categoria );

CREATE TABLE tbl_centros_regionales (
    codigo_centro_regional INTEGER NOT NULL,
    codigo_lugar           NUMBER NOT NULL,
    nombre                 VARCHAR2(80) NOT NULL,
    direccion              VARCHAR2(500),
    siglas                 VARCHAR2(20) NOT NULL
);

ALTER TABLE tbl_centros_regionales ADD CONSTRAINT tbl_centros_regionales_pk PRIMARY KEY ( codigo_centro_regional );

CREATE TABLE tbl_departamentos (
    codigo_departamento NUMBER NOT NULL,
    codigo_pais         NUMBER NOT NULL,
    nombre              VARCHAR2(300)
);

ALTER TABLE tbl_departamentos ADD CONSTRAINT tbl_departamentos_pk PRIMARY KEY ( codigo_departamento );

CREATE TABLE tbl_edificios (
    codigo_edificio        NUMBER NOT NULL,
    codigo_centro_regional INTEGER NOT NULL,
    nombre_edificio        VARCHAR2(100),
    direccion              VARCHAR2(200)
);

ALTER TABLE tbl_edificios ADD CONSTRAINT tbl_edificios_pk PRIMARY KEY ( codigo_edificio );

CREATE TABLE tbl_empleados (
    codigo_empleado NUMBER NOT NULL,
    salario         NUMBER,
    codigo_perfil   NUMBER NOT NULL
);

ALTER TABLE tbl_empleados ADD CONSTRAINT tbl_empleados_pk PRIMARY KEY ( codigo_empleado );

CREATE TABLE tbl_estados_historial (
    codigo_estado_historial NUMBER NOT NULL,
    descripcion             VARCHAR2(50)
);

ALTER TABLE tbl_estados_historial ADD CONSTRAINT tbl_estados_historial_pk PRIMARY KEY ( codigo_estado_historial );

CREATE TABLE tbl_estados_matricula (
    codigo_estado NUMBER NOT NULL,
    nombre_estado VARCHAR2(200),
    descripcion   VARCHAR2(300)
);

ALTER TABLE tbl_estados_matricula ADD CONSTRAINT tbl_estados_matricula_pk PRIMARY KEY ( codigo_estado );

CREATE TABLE tbl_historiales (
    codigo_historial        NUMBER NOT NULL,
    codigo_matricula        NUMBER NOT NULL,
    codigo_estado_historial NUMBER NOT NULL,
    promedio                NUMBER
);

ALTER TABLE tbl_historiales ADD CONSTRAINT tbl_historiales_pk PRIMARY KEY ( codigo_historial );

CREATE TABLE tbl_lugares (
    codigo_lugar       NUMBER NOT NULL,
    codigo_lugar_padre NUMBER,
    codigo_tipo_lugar  NUMBER NOT NULL,
    nombre_lugar       VARCHAR2(300),
    longitud           NUMBER,
    latitud            NUMBER,
    extension          NUMBER
);

ALTER TABLE tbl_lugares ADD CONSTRAINT tbl_lugares_pk PRIMARY KEY ( codigo_lugar );

CREATE TABLE tbl_maestros (
    codigo_maestro       NUMBER NOT NULL,
    unidades_valorativas NUMBER,
    codigo_categoria     NUMBER
);

ALTER TABLE tbl_maestros ADD CONSTRAINT tbl_maestros_pk PRIMARY KEY ( codigo_maestro );

CREATE TABLE tbl_matricula (
    codigo_matricula NUMBER NOT NULL,
    codigo_seccion   NUMBER NOT NULL,
    codigo_alumno    NUMBER NOT NULL,
    codigo_estado    NUMBER NOT NULL,
    numero_lista     NUMBER
);

ALTER TABLE tbl_matricula ADD CONSTRAINT tbl_matricula_pk PRIMARY KEY ( codigo_matricula );

CREATE TABLE tbl_municipios (
    codigo_municipio    NUMBER NOT NULL,
    codigo_departamento NUMBER NOT NULL,
    nombre              VARCHAR2(300)
);

ALTER TABLE tbl_municipios ADD CONSTRAINT tbl_municipios_pk PRIMARY KEY ( codigo_municipio );

CREATE TABLE tbl_paises (
    codigo_pais NUMBER NOT NULL,
    nombre      VARCHAR2(300)
);

ALTER TABLE tbl_paises ADD CONSTRAINT tbl_paises_pk PRIMARY KEY ( codigo_pais );

CREATE TABLE tbl_perfiles (
    codigo_perfil  NUMBER NOT NULL,
    nombre_perfil  VARCHAR2(200),
    salario_minimo NUMBER,
    salario_maximo NUMBER
);

ALTER TABLE tbl_perfiles ADD CONSTRAINT tbl_perfiles_pk PRIMARY KEY ( codigo_perfil );

CREATE TABLE tbl_periodos (
    codigo_periodo VARCHAR2(10) NOT NULL,
    fecha_inicio   DATE,
    fecha_fin      DATE
);

ALTER TABLE tbl_periodos ADD CONSTRAINT tbl_periodos_pk PRIMARY KEY ( codigo_periodo );

CREATE TABLE tbl_personas (
    codigo                  NUMBER NOT NULL,
    codigo_centro_regional  INTEGER NOT NULL,
    codigo_municipio        NUMBER NOT NULL,
    codigo_lugar_nacimiento NUMBER NOT NULL,
    codigo_lugar_residencia NUMBER NOT NULL,
    identificacion          VARCHAR2(20) NOT NULL,
    nombre                  VARCHAR2(50) NOT NULL,
    apellido                VARCHAR2(50),
    correo                  VARCHAR2(500) NOT NULL,
    fecha_nacimiento        DATE,
    direccion               VARCHAR2(500)
);

CREATE UNIQUE INDEX tbl_personas_correo_idx ON
    tbl_personas (
        correo
    ASC );

ALTER TABLE tbl_personas ADD CONSTRAINT tbl_personas_pk PRIMARY KEY ( codigo );

CREATE TABLE tbl_requisitos (
    codigo            NUMBER NOT NULL,
    codigo_asignatura NUMBER NOT NULL,
    codigo_requisito  NUMBER NOT NULL,
    codigo_carrera    NUMBER NOT NULL,
    aprobado          CHAR(1)
);

ALTER TABLE tbl_requisitos ADD CONSTRAINT tbl_requisitos_pk PRIMARY KEY ( codigo );

CREATE TABLE tbl_secciones (
    codigo_seccion             NUMBER NOT NULL,
    codigo_seccion_alternativo VARCHAR2(200),
    codigo_periodo             VARCHAR2(10) NOT NULL,
    codigo_edificio            NUMBER NOT NULL,
    codigo_maestro             NUMBER NOT NULL,
    codigo_asignatura          NUMBER NOT NULL,
    cantidad_cupos             NUMBER,
    numero_aula                NUMBER
);

ALTER TABLE tbl_secciones ADD CONSTRAINT tbl_secciones_pk PRIMARY KEY ( codigo_seccion );

CREATE TABLE tbl_tipos_lugares (
    codigo_tipo_lugar NUMBER NOT NULL,
    nombre_tipo       VARCHAR2(100) NOT NULL
);

ALTER TABLE tbl_tipos_lugares ADD CONSTRAINT tbl_tipos_lugares_pk PRIMARY KEY ( codigo_tipo_lugar );

ALTER TABLE tbl_alumnos_x_carreras
    ADD CONSTRAINT alu_x_carr_alu_fk FOREIGN KEY ( codigo_alumno )
        REFERENCES tbl_alumnos ( codigo_alumno );

ALTER TABLE tbl_alumnos_x_carreras
    ADD CONSTRAINT alu_x_carr_tbl_carr_fk FOREIGN KEY ( codigo_carrera )
        REFERENCES tbl_carreras ( codigo_carrera );

ALTER TABLE tbl_asignaturas
    ADD CONSTRAINT asig_car_fk FOREIGN KEY ( codigo_carrera )
        REFERENCES tbl_carreras ( codigo_carrera );

ALTER TABLE tbl_carreras
    ADD CONSTRAINT car_emple_fkv2 FOREIGN KEY ( codigo_coordinador )
        REFERENCES tbl_empleados ( codigo_empleado );

ALTER TABLE tbl_centros_regionales
    ADD CONSTRAINT cen_regi_lug_fk FOREIGN KEY ( codigo_lugar )
        REFERENCES tbl_lugares ( codigo_lugar );

ALTER TABLE tbl_departamentos
    ADD CONSTRAINT dep_pai_fk FOREIGN KEY ( codigo_pais )
        REFERENCES tbl_paises ( codigo_pais );

ALTER TABLE tbl_edificios
    ADD CONSTRAINT edif_cen_reg_fk FOREIGN KEY ( codigo_centro_regional )
        REFERENCES tbl_centros_regionales ( codigo_centro_regional );

ALTER TABLE tbl_historiales
    ADD CONSTRAINT his_tbl_est_his_fk FOREIGN KEY ( codigo_estado_historial )
        REFERENCES tbl_estados_historial ( codigo_estado_historial );

ALTER TABLE tbl_historiales
    ADD CONSTRAINT histmatr_fk FOREIGN KEY ( codigo_matricula )
        REFERENCES tbl_matricula ( codigo_matricula );

ALTER TABLE tbl_lugares
    ADD CONSTRAINT lug_ti_lug_fk FOREIGN KEY ( codigo_tipo_lugar )
        REFERENCES tbl_tipos_lugares ( codigo_tipo_lugar );

ALTER TABLE tbl_maestros
    ADD CONSTRAINT mae_cat_mae_fk FOREIGN KEY ( codigo_categoria )
        REFERENCES tbl_categorias_maestros ( codigo_categoria );

ALTER TABLE tbl_matricula
    ADD CONSTRAINT mat_est_mat_fk FOREIGN KEY ( codigo_estado )
        REFERENCES tbl_estados_matricula ( codigo_estado );

ALTER TABLE tbl_municipios
    ADD CONSTRAINT mun_dep_fk FOREIGN KEY ( codigo_departamento )
        REFERENCES tbl_departamentos ( codigo_departamento );

ALTER TABLE tbl_personas
    ADD CONSTRAINT per_cen_reg_fk FOREIGN KEY ( codigo_centro_regional )
        REFERENCES tbl_centros_regionales ( codigo_centro_regional );

ALTER TABLE tbl_requisitos
    ADD CONSTRAINT req_asig_fkv2 FOREIGN KEY ( codigo_requisito )
        REFERENCES tbl_asignaturas ( codigo_asignatura );

ALTER TABLE tbl_requisitos
    ADD CONSTRAINT requi_asig_fk FOREIGN KEY ( codigo_asignatura )
        REFERENCES tbl_asignaturas ( codigo_asignatura );

ALTER TABLE tbl_requisitos
    ADD CONSTRAINT requi_car_fk FOREIGN KEY ( codigo_carrera )
        REFERENCES tbl_carreras ( codigo_carrera );

ALTER TABLE tbl_secciones
    ADD CONSTRAINT secc_asig_fk FOREIGN KEY ( codigo_asignatura )
        REFERENCES tbl_asignaturas ( codigo_asignatura );

ALTER TABLE tbl_alumnos
    ADD CONSTRAINT tbl_alumnos_tbl_personas_fk FOREIGN KEY ( codigo_alumno )
        REFERENCES tbl_personas ( codigo );

ALTER TABLE tbl_carreras
    ADD CONSTRAINT tbl_carreras_tbl_empleados_fk FOREIGN KEY ( codigo_jefe )
        REFERENCES tbl_empleados ( codigo_empleado );

ALTER TABLE tbl_empleados
    ADD CONSTRAINT tbl_empleados_tbl_perfiles_fk FOREIGN KEY ( codigo_perfil )
        REFERENCES tbl_perfiles ( codigo_perfil );

ALTER TABLE tbl_empleados
    ADD CONSTRAINT tbl_empleados_tbl_personas_fk FOREIGN KEY ( codigo_empleado )
        REFERENCES tbl_personas ( codigo );

ALTER TABLE tbl_lugares
    ADD CONSTRAINT tbl_lugares_tbl_lugares_fk FOREIGN KEY ( codigo_lugar_padre )
        REFERENCES tbl_lugares ( codigo_lugar );

ALTER TABLE tbl_maestros
    ADD CONSTRAINT tbl_maestros_tbl_empleados_fk FOREIGN KEY ( codigo_maestro )
        REFERENCES tbl_empleados ( codigo_empleado );

ALTER TABLE tbl_matricula
    ADD CONSTRAINT tbl_matricula_tbl_alumnos_fk FOREIGN KEY ( codigo_alumno )
        REFERENCES tbl_alumnos ( codigo_alumno );

ALTER TABLE tbl_matricula
    ADD CONSTRAINT tbl_matricula_tbl_secciones_fk FOREIGN KEY ( codigo_seccion )
        REFERENCES tbl_secciones ( codigo_seccion );

ALTER TABLE tbl_personas
    ADD CONSTRAINT tbl_personas_tbl_lugares_fk FOREIGN KEY ( codigo_lugar_nacimiento )
        REFERENCES tbl_lugares ( codigo_lugar );

ALTER TABLE tbl_personas
    ADD CONSTRAINT tbl_personas_tbl_lugares_fkv2 FOREIGN KEY ( codigo_lugar_residencia )
        REFERENCES tbl_lugares ( codigo_lugar );

ALTER TABLE tbl_personas
    ADD CONSTRAINT tbl_personas_tbl_municipios_fk FOREIGN KEY ( codigo_municipio )
        REFERENCES tbl_municipios ( codigo_municipio );

ALTER TABLE tbl_secciones
    ADD CONSTRAINT tbl_secciones_tbl_edificios_fk FOREIGN KEY ( codigo_edificio )
        REFERENCES tbl_edificios ( codigo_edificio );

ALTER TABLE tbl_secciones
    ADD CONSTRAINT tbl_secciones_tbl_maestros_fk FOREIGN KEY ( codigo_maestro )
        REFERENCES tbl_maestros ( codigo_maestro );

ALTER TABLE tbl_secciones
    ADD CONSTRAINT tbl_secciones_tbl_periodos_fk FOREIGN KEY ( codigo_periodo )
        REFERENCES tbl_periodos ( codigo_periodo );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            23
-- CREATE INDEX                             1
-- ALTER TABLE                             55
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0