-- USER SQL
CREATE USER "BD_UNAH" IDENTIFIED BY "oracle"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "BD_UNAH" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "BD_UNAH" ;
GRANT "RESOURCE" TO "BD_UNAH" ;

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "BD_UNAH" ;
GRANT CREATE VIEW TO "BD_UNAH" ;
GRANT CREATE TABLE TO "BD_UNAH" ;
GRANT CREATE TYPE TO "BD_UNAH" ;
GRANT CREATE SEQUENCE TO "BD_UNAH" ;

